[package]
name = "milstian-internet-framework"
version = "0.1.1"
authors = ["Christian Johansson <christian@cvj.se>"]
description = "A internet framework"
license = "GPL-3.0-only"

[dependencies]
chrono = "0.4"
milstian-http = "0.1.*"